import type { CharacterDefinition, HitBox } from '@battleborn/game-core';

function hitbox(hit: HitBox): HitBox {
  return hit;
}

const morana: CharacterDefinition = {
  id: 'morana',
  name: 'Morana',
  palette: {
    primary: '#37d4ff',
    accent: '#fff07f',
    shadow: '#0d2f44',
  },
  sprites: {
    portrait: '/characters/morana/profile.png',
    renderHeight: 120,
    stanceAliases: {
      // Many characters don't ship a dedicated guard animation yet.
      // Falling back prevents extra asset scans and missing-frame glitches.
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 0.42,
    arenaMovement: {
      preferredDistanceMultiplier: 1.18,
      approachBias: 0.34,
      retreatBias: 0.82,
      jumpInChance: 0.18,
      dashJumpForwardChance: 0.22,
      dashJumpBackwardChance: 0.76,
    },
    skillChoice: {
      punchWeight: 1.5,
      kickWeight: 0.85,
      specialWeight: 1.15,
      attackCadenceMultiplier: 1.02,
    },
    defense: {
      blockChance: 0.96,
      projectileDodgeChance: 0.68,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 6,
    },
  },
  stats: {
    maxHealth: 1000,
    movement: {
      walkSpeed: 5.5,
      jumpVelocity: 18,
      gravity: 1.1,
      dash: {
        distance: 92.4,
        speed: 6.55,
        lift: 8.2,
      },
    },
    pushWidth: 24,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -110, width: 44, height: 110 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -96, width: 48, height: 96 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Q1',
      button: 'punch',
      startup: 3,
      active: 1,
      recovery: 9,
      cooldownSeconds: 1.2,
      projectile: {
        sprite: 'morana/iceball',
        tier: 2,
        spriteScale: 1,
        offsetX: 24,
        offsetY: -55,
        speed: 8,
        minimumDistanceRatio: 0.5,
        maximumDistanceRatio: 0.5,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -16,
          y: -16,
          width: 32,
          height: 32,
          damage: 60,
          hitstun: 10,
          knockbackX: 7,
        }),
      },
    },
    kick: {
      id: 'kick',
      label: 'Flash Arc',
      button: 'kick',
      startup: 3,
      active: 1,
      recovery: 16,
      cooldownSeconds: 0.9,
      phaseThroughProjectiles: true,
      relocation: {
        startFrame: 3,
        endFrame: 4,
        distanceXRatio: 0.5,
      },
      hitboxAnchor: 'attack-origin',
      effectAnimation: {
        // TODO: swap back to 'characters/morana/animations/attack2-effect' once the asset exists.
        sprite: 'characters/morana/animations/attack2',
        startFrame: 3,
        offsetX: 35,
        offsetY: -63,
        anchor: 'attack-origin',
        playbackRate: 0.5,
      },
      frameBoxes: {
        3: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -72,
              width: 30,
              height: 18,
              damage: 85,
              freezeFrames: 120,
              hitstun: 12,
              knockbackX: 9,
              launchY: 4,
            }),
          ],
        },
      },
    },
    special: {
      id: 'special',
      label: 'Frost Barrage',
      button: 'special',
      startup: 10,
      active: 1,
      recovery: 60,
      cooldownSeconds: 1.6,
      interruptible: false,
      specialSequence: {
        buildUpFrames: 10,
        animationBuildUpFrames: 10,
        buildUpAnimation: 'special-pose',
        animationMode: 'loop',
        loopFrameDuration: 4,
        channelMoveSpeed: 3.2,
        hoverHeight: 10,
        zoomOutFrames: 6,
        zoomScale: 1.76,
      },
      projectile: {
        sprite: 'morana/special',
        tier: 2,
        spawnFrame: 11,
        shotCount: 3,
        shotIntervalFrames: 30,
        offsetX: 26,
        offsetY: -58,
        speed: 10.5,
        minimumDistanceRatio: 0.7,
        maximumDistanceRatio: 0.7,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -18,
          y: -18,
          width: 36,
          height: 36,
          damage: 42,
          hitstun: 9,
          knockbackX: 6,
        }),
      },
    },
  },
};

const mcbalut: CharacterDefinition = {
  id: 'mcbalut',
  name: 'mcbalut',
  palette: {
    primary: '#7de06e',
    accent: '#f6dd67',
    shadow: '#1d3b28',
  },
  sprites: {
    portrait: '/characters/mcbalut/profile.png',
    renderHeight: 110,
    stanceAliases: {
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 1,
    arenaMovement: {
      preferredDistanceMultiplier: 0.72,
      approachBias: 1,
      retreatBias: 0,
      jumpInChance: 1,
      dashJumpForwardChance: 1,
      dashJumpBackwardChance: 1,
    },
    skillChoice: {
      punchWeight: 2,
      kickWeight: 2,
      specialWeight: 2,
      attackCadenceMultiplier: 0.7,
    },
    defense: {
      blockChance: 1,
      projectileDodgeChance: 1,
      meleeBlockReactionFrames: 2,
      projectileBlockReactionFrames: 8,
    },
  },
  stats: {
    maxHealth: 1020,
    movement: {
      walkSpeed: 3,
      jumpVelocity: 17,
      gravity: 1.08,
      dash: {
        distance: 108,
        speed: 13.5,
        lift: 3.4,
      },
    },
    pushWidth: 24,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -110, width: 44, height: 110 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -96, width: 48, height: 96 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Q1',
      button: 'punch',
      startup: 5,
      active: 1,
      recovery: 11,
      cooldownSeconds: 1,
      projectile: {
        sprite: 'mcbalut/crossbow-bolt',
        tier: 1,
        rotateToVelocity: false,
        spriteScale: 1,
        offsetX: 42,
        offsetY: -60,
        speed: 17.75,
        minimumDistanceRatio: 0.55,
        apexHeight: 42,
        landing: 'floor',
        hitbox: hitbox({
          x: -18,
          y: -4,
          width: 36,
          height: 8,
          damage: 62,
          hitstun: 11,
          knockbackX: 8,
        }),
      },
    },
    kick: {
      id: 'kick',
      label: 'Prototype Arc',
      button: 'kick',
      startup: 6,
      active: 3,
      recovery: 14,
      cooldownSeconds: 0.9,
      projectile: {
        sprite: 'mcbalut/crossbow-bolt',
        tier: 1,
        rotateToVelocity: false,
        spawnFrame: 6,
        shotCount: 3,
        shotIntervalFrames: 5,
        offsetX: 42,
        offsetY: -60,
        speed: 22,
        targeting: 'opponent',
        homing: true,
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -16,
          y: -4,
          width: 32,
          height: 8,
          damage: 44,
          hitstun: 10,
          knockbackX: 6,
        }),
        shotHitboxes: [
          hitbox({
            x: -16,
            y: -4,
            width: 32,
            height: 8,
            damage: 44,
            hitstun: 10,
            knockbackX: 6,
          }),
          hitbox({
            x: -16,
            y: -4,
            width: 32,
            height: 8,
            damage: 44,
            hitstun: 10,
            knockbackX: 6,
          }),
          hitbox({
            x: -16,
            y: -4,
            width: 32,
            height: 8,
            damage: 44,
            hitstun: 10,
            knockbackX: 14,
          }),
        ],
      },
    },
    special: {
      id: 'special',
      label: 'Prototype Burst',
      button: 'special',
      startup: 16,
      active: 2,
      recovery: 16,
      cooldownSeconds: 10,
      specialSequence: {
        buildUpFrames: 16,
        animationBuildUpFrames: 11,
        pauseFrames: 8,
        zoomOutFrames: 8,
        holdUntilGroundedAfterBuildUp: true,
        zoomScale: 1.88,
      },
      projectile: {
        sprite: 'mcbalut/crossbow-bolt',
        tier: 1,
        rotateToVelocity: false,
        spawnFrame: 28,
        offsetX: 42,
        offsetY: -60,
        speed: 35.5,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -20,
          y: -5,
          width: 40,
          height: 10,
          damage: 115,
          hitstun: 18,
          knockbackX: 14,
        }),
      },
    },
  },
};

export const mcbalutAnomaly: CharacterDefinition = {
  id: 'mcbalut-anomaly',
  name: 'mcbalut',
  palette: {
    primary: '#7de06e',
    accent: '#f6dd67',
    shadow: '#1d3b28',
  },
  sprites: {
    portrait: '/characters/mcbalut-anomaly/profile.png',
    renderHeight: 128,
    assetRoot: 'mcbalut-anomaly',
    stanceAliases: {
      special: ['attack2'],
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 1,
    arenaMovement: {
      preferredDistanceMultiplier: 1.04,
      approachBias: 0.78,
      retreatBias: 0.16,
      jumpInChance: 0.22,
      dashJumpForwardChance: 0.36,
      dashJumpBackwardChance: 0.18,
    },
    skillChoice: {
      punchWeight: 2.8,
      kickWeight: 2.5,
      specialWeight: 1.9,
      attackCadenceMultiplier: 0.4,
    },
    defense: {
      blockChance: 1,
      projectileDodgeChance: 1,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 2,
    },
  },
  stats: {
    maxHealth: 1060,
    movement: {
      walkSpeed: 6.2,
      jumpVelocity: 18.5,
      gravity: 1.02,
      dash: {
        distance: 138,
        speed: 15.5,
        lift: 4.4,
      },
    },
    pushWidth: 24,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -110, width: 44, height: 110 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -96, width: 48, height: 96 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Anomaly Shot',
      button: 'punch',
      startup: 4,
      active: 1,
      recovery: 8,
      cooldownSeconds: 0.35,
      projectile: {
        sprite: 'mcbalut/crossbow-bolt',
        tier: 99,
        guardBypass: true,
        offsetX: 44,
        offsetY: -62,
        speed: 27,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -20,
          y: -5,
          width: 40,
          height: 10,
          damage: 82,
          hitstun: 13,
          knockbackX: 11,
        }),
      },
    },
    kick: {
      id: 'kick',
      label: 'Rift Splitter',
      button: 'kick',
      startup: 5,
      active: 1,
      recovery: 30,
      cooldownSeconds: 0.45,
      projectile: {
        sprite: 'characters/mcbalut-anomaly/animations/attack2-projectile',
        tier: 99,
        guardBypass: true,
        spawnFrame: 30,
        // Keep the sprite's authored orientation (don't rotate to travel direction),
        // so it doesn't "fall on its side" when dropping vertically.
        rotateToVelocity: false,
        rotationOffsetRadians: 0,
        spriteScale: 0.6,
        // 0.5x speed (2x slower)
        animationFrameDurationFrames: 4,
        spawnAnchor: 'opponent',
        offsetX: 0,
        offsetY: -360,
        speed: 4.5,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -18,
          y: -18,
          width: 36,
          height: 56,
          damage: 108,
          hitstun: 16,
          knockbackX: 14,
        }),
      },
    },
    special: {
      id: 'special',
      label: 'Anomaly Barrage',
      button: 'special',
      startup: 14,
      active: 2,
      recovery: 104,
      cooldownSeconds: 6.5,
      specialSequence: {
        buildUpFrames: 37,
        animationBuildUpFrames: 37,
        loopFrameDuration: 6,
        freezeOpponentDuringBuildUp: false,
        holdUntilGroundedAfterBuildUp: true,
        zoomScale: 1.9,
      },
      projectile: {
        sprite: 'characters/mcbalut-anomaly/animations/special-projectile',
        tier: 99,
        guardBypass: true,
        spawnFrame: 38,
        lifetimeFrames: 84,
        persistsOnHit: true,
        hitIntervalFrames: 60,
        spriteScale: 0.56,
        animationFrameDurationFrames: 6,
        offsetX: 500,
        offsetY: -60,
        speed: 0.001,
        targeting: 'forward',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -480,
          y: -24,
          width: 960,
          height: 48,
          damage: 120,
          chipDamage: 0,
          hitstun: 14,
          knockbackX: 10,
        }),
      },
    },
  },
};

const digv: CharacterDefinition = {
  id: 'digv',
  name: 'DigV',
  palette: {
    primary: '#7d8fff',
    accent: '#f2be67',
    shadow: '#1d2550',
  },
  sprites: {
    portrait: '/characters/digv/profile.png',
    renderHeight: 100,
    stanceAliases: {
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 0.64,
    arenaMovement: {
      preferredDistanceMultiplier: 0.98,
      approachBias: 0.7,
      retreatBias: 0.4,
      jumpInChance: 0.46,
      dashJumpForwardChance: 0.62,
      dashJumpBackwardChance: 0.34,
    },
    skillChoice: {
      punchWeight: 1.1,
      kickWeight: 0.94,
      specialWeight: 1.28,
      attackCadenceMultiplier: 0.92,
    },
    defense: {
      blockChance: 0.86,
      projectileDodgeChance: 0.58,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 1010,
    movement: {
      walkSpeed: 2.8,
      jumpVelocity: 17,
      gravity: 1.08,
      dash: {
        distance: 108.04,
        speed: 5.7,
        lift: 8.4,
      },
    },
    pushWidth: 24,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -110, width: 44, height: 110 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -96, width: 48, height: 96 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Prototype Jab',
      button: 'punch',
      startup: 4,
      active: 1,
      recovery: 10,
      cooldownSeconds: 0.6,
      projectile: {
        sprite: 'digv/fireball',
        tier: 2,
        spriteScale: 1,
        offsetX: 24,
        offsetY: -55,
        speed: 8,
        minimumDistanceRatio: 0.6,
        maximumDistanceRatio: 0.6,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -10.67,
          y: -10.67,
          width: 21.33,
          height: 21.33,
          damage: 65,
          hitstun: 10,
          knockbackX: 8,
        }),
      },
    },
    kick: {
      id: 'kick',
      label: 'Prototype Arc',
      button: 'kick',
      startup: 6,
      // Full projectile animation is 9 frames; at 3 frames per frame => 27 frames.
      // Play it 3 times => 81 active frames.
      active: 81,
      recovery: 18,
      cooldownSeconds: 2,
      animationStance: 'attack2',
      projectile: {
        sprite: 'characters/digv/animations/attack2-projectile',
        tier: 2,
        rotateToVelocity: false,
        spawnFrame: 6,
        shotCount: 3,
        // Animate the full 9-frame sequence per shot (9 * 3 = 27 frames), three times.
        shotIntervalFrames: 27,
        spriteScale: 1,
        animationFrameDurationFrames: 3,
        offsetX: 105,
        offsetY: -62,
        // Stationary flame: keep movement effectively zero.
        speed: 0.001,
        lifetimeFrames: 27,
        targeting: 'forward',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -36,
          y: -18,
          width: 72,
          height: 36,
          damage: 28,
          hitstun: 9,
          knockbackX: 2,
          launchY: 2,
        }),
        shotHitboxes: [
          hitbox({
            x: -36,
            y: -18,
            width: 72,
            height: 36,
            damage: 28,
            hitstun: 9,
            knockbackX: 2,
            launchY: 2,
          }),
          hitbox({
            x: -36,
            y: -18,
            width: 72,
            height: 36,
            damage: 28,
            hitstun: 9,
            knockbackX: 2,
            launchY: 2,
          }),
          hitbox({
            x: -40,
            y: -20,
            width: 80,
            height: 40,
            damage: 40,
            hitstun: 13,
            knockbackX: 13,
            launchY: 5,
          }),
        ],
      },
    },
    special: {
      id: 'special',
      label: 'Meteor Drop',
      button: 'special',
      startup: 10,
      active: 1,
      recovery: 18,
      cooldownSeconds: 0,
      specialSequence: {
        buildUpFrames: 10,
        pauseFrames: 6,
        zoomOutFrames: 7,
        completeAnimationDuringZoomOut: true,
        zoomScale: 1.82,
      },
      projectile: {
        sprite: 'digv/special',
        tier: 2,
        spriteScale: 2,
        spawnFrame: 11,
        spawnAnchor: 'opponent',
        offsetX: 0,
        offsetY: -240,
        // 1/4 speed (4x slower landing).
        speed: 6,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -22,
          y: -26,
          width: 44,
          height: 44,
          damage: 120,
          hitstun: 18,
          knockbackX: 12,
          launchY: 7,
        }),
      },
    },
  },
};

const paraktaktak: CharacterDefinition = {
  id: 'paraktaktak',
  name: 'ParakTakTak',
  palette: {
    primary: '#e3c25d',
    accent: '#f79642',
    shadow: '#403117',
  },
  sprites: {
    portrait: '/characters/paraktaktak/profile.png',
    renderHeight: 132,
    stanceAliases: {
      attack1: ['attack1a'],
      'special-loop': ['special'],
    },
    stanceFrameDurations: {
      'special-wind-up': 3,
      special: 3,
    },
    stanceRenderOffsets: {
      attack2: { y: 18 },
    },
  },
  bot: {
    aggressiveness: 0.84,
    arenaMovement: {
      preferredDistanceMultiplier: 0.84,
      approachBias: 0.92,
      retreatBias: 0.16,
      jumpInChance: 0.82,
      dashJumpForwardChance: 0.9,
      dashJumpBackwardChance: 0.12,
    },
    skillChoice: {
      punchWeight: 1.4,
      kickWeight: 1.08,
      specialWeight: 0.92,
      attackCadenceMultiplier: 0.76,
    },
    defense: {
      blockChance: 0.74,
      projectileDodgeChance: 0.34,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 3,
    },
  },
  stats: {
    maxHealth: 1030,
    movement: {
      walkSpeed: 3.1,
      jumpVelocity: 17,
      gravity: 1.08,
      dash: {
        distance: 104,
        speed: 8.625,
        lift: 6,
      },
    },
    pushWidth: 24,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -110, width: 44, height: 110 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -96, width: 48, height: 96 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Tak Strike 1',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 12,
      cooldownSeconds: 0.55,
      meleeRange: 150,
      interruptible: true,
      animationStance: 'attack1',
      followUpMoveId: 'punch2',
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.035,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 28,
              y: -84,
              width: 78,
              height: 18,
              damage: 60,
              hitstun: 9,
              knockbackX: 6,
            }),
          ],
        },
      },
    },
    punch2: {
      id: 'punch2',
      label: 'Tak Strike 2',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 12,
      cooldownSeconds: 0,
      meleeRange: 160,
      interruptible: true,
      animationStance: 'attack1b',
      followUpMoveId: 'punch3',
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.04,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 32,
              y: -84,
              width: 84,
              height: 18,
              damage: 58,
              hitstun: 9,
              knockbackX: 6,
            }),
          ],
        },
      },
    },
    punch3: {
      id: 'punch3',
      label: 'Tak Strike 3',
      button: 'punch',
      startup: 5,
      active: 2,
      recovery: 14,
      cooldownSeconds: 0,
      meleeRange: 170,
      animationStance: 'attack1c',
      relocation: {
        startFrame: 4,
        endFrame: 6,
        distanceXRatio: 0.045,
      },
      frameBoxes: {
        5: {
          hitboxes: [
            hitbox({
              x: 36,
              y: -84,
              width: 92,
              height: 18,
              damage: 72,
              hitstun: 11,
              knockbackX: 10,
              launchY: 3,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Parak Blitz',
      button: 'kick',
      startup: 6,
      active: 4,
      recovery: 14,
      cooldownSeconds: 0.85,
      meleeRange: 268,
      animationStance: 'attack2',
      multiHit: true,
      phaseThroughProjectiles: true,
      relocation: {
        startFrame: 4,
        endFrame: 9,
        distanceXRatio: 0.25,
      },
      hitboxAnchor: 'attack-origin',
      frameBoxes: {
        6: {
          hitboxes: [
            hitbox({
              x: -8,
              y: -128,
              width: 258,
              height: 128,
              damage: 46,
              hitstun: 8,
              knockbackX: 7,
            }),
            hitbox({
              x: 18,
              y: -164,
              width: 72,
              height: 48,
              damage: 46,
              hitstun: 8,
              knockbackX: 7,
            }),
            hitbox({
              x: 82,
              y: -156,
              width: 116,
              height: 56,
              damage: 46,
              hitstun: 8,
              knockbackX: 7,
            }),
            hitbox({
              x: 196,
              y: -118,
              width: 72,
              height: 94,
              damage: 46,
              hitstun: 8,
              knockbackX: 7,
            }),
          ],
        },
        9: {
          hitboxes: [
            hitbox({
              x: -8,
              y: -128,
              width: 258,
              height: 128,
              damage: 46,
              hitstun: 9,
              knockbackX: 9,
              launchY: 2,
            }),
            hitbox({
              x: 18,
              y: -164,
              width: 72,
              height: 48,
              damage: 46,
              hitstun: 9,
              knockbackX: 9,
              launchY: 2,
            }),
            hitbox({
              x: 82,
              y: -156,
              width: 116,
              height: 56,
              damage: 46,
              hitstun: 9,
              knockbackX: 9,
              launchY: 2,
            }),
            hitbox({
              x: 196,
              y: -118,
              width: 72,
              height: 94,
              damage: 46,
              hitstun: 9,
              knockbackX: 9,
              launchY: 2,
            }),
          ],
        },
      },
    },
    special: {
      id: 'special',
      label: 'Tak Breaker',
      button: 'special',
      startup: 27,
      active: 10,
      recovery: 44,
      cooldownSeconds: 1.45,
      meleeRange: 104,
      multiHit: true,
      specialSequence: {
        buildUpFrames: 27,
        animationBuildUpFrames: 9,
        buildUpAnimation: 'special-wind-up',
        pauseFrames: 5,
        zoomOutFrames: 6,
        zoomScale: 1.82,
      },
      relocation: {
        startFrame: 27,
        endFrame: 36,
        distanceXRatio: 0.14,
      },
      frameBoxes: {
        27: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -92,
              width: 88,
              height: 28,
              damage: 32,
              hitstun: 10,
              knockbackX: 2,
            }),
          ],
          hurtboxes: [{ x: -20, y: -108, width: 52, height: 108 }],
        },
        30: {
          hitboxes: [
            hitbox({
              x: 24,
              y: -92,
              width: 92,
              height: 30,
              damage: 32,
              hitstun: 10,
              knockbackX: 2,
            }),
          ],
          hurtboxes: [{ x: -20, y: -108, width: 52, height: 108 }],
        },
        33: {
          hitboxes: [
            hitbox({
              x: 28,
              y: -94,
              width: 98,
              height: 32,
              damage: 32,
              hitstun: 11,
              knockbackX: 3,
            }),
          ],
          hurtboxes: [{ x: -20, y: -108, width: 52, height: 108 }],
        },
        36: {
          hitboxes: [
            hitbox({
              x: 32,
              y: -96,
              width: 106,
              height: 34,
              damage: 34,
              hitstun: 16,
              knockbackX: 10,
              launchY: 6,
            }),
          ],
          hurtboxes: [{ x: -20, y: -108, width: 52, height: 108 }],
        },
      },
    },
  },
};

const distorted: CharacterDefinition = {
  id: 'distorted',
  name: 'Distorted',
  palette: {
    primary: '#91b3ff',
    accent: '#f2d06a',
    shadow: '#1b1f36',
  },
  sprites: {
    portrait: '/characters/distorted09/animations/portrait.png',
    renderHeight: 108,
    assetRoot: 'distorted09',
    stanceAliases: {
      attack1: ['attack1a'],
      special: ['special-a'],
      'special-loop': ['special-b'],
      'special-c': ['special-b'],
    },
  },
  bot: {
    aggressiveness: 0.72,
    arenaMovement: {
      preferredDistanceMultiplier: 0.88,
      approachBias: 0.8,
      retreatBias: 0.22,
      jumpInChance: 0.54,
      dashJumpForwardChance: 0.7,
      dashJumpBackwardChance: 0.18,
    },
    skillChoice: {
      punchWeight: 1.16,
      kickWeight: 1.04,
      specialWeight: 1.18,
      attackCadenceMultiplier: 0.84,
    },
    defense: {
      blockChance: 0.74,
      projectileDodgeChance: 0.4,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 3,
    },
  },
  stats: {
    maxHealth: 990,
    movement: {
      walkSpeed: 4.35,
      jumpVelocity: 18.4,
      gravity: 1.06,
      dash: {
        distance: 114,
        speed: 9.5,
        lift: 6.2,
      },
    },
    pushWidth: 22,
  },
  standingBoxes: {
    hurtboxes: [{ x: -21, y: -104, width: 42, height: 104 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -23, y: -92, width: 46, height: 92 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Glitch Jab',
      button: 'punch',
      startup: 4,
      active: 3,
      recovery: 9,
      cooldownSeconds: 0,
      animationStance: 'attack1',
      followUpMoveId: 'punchFollowUp',
      meleeRange: 74,
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.035,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 18,
              y: -78,
              width: 28,
              height: 16,
              damage: 64,
              hitstun: 10,
              knockbackX: 8,
            }),
          ],
        },
      },
    },
    punchFollowUp: {
      id: 'punchFollowUp',
      label: 'Phase Split',
      button: 'punch',
      startup: 5,
      active: 4,
      recovery: 11,
      cooldownSeconds: 0,
      animationStance: 'attack1b',
      followUpMoveId: 'punchFinisher',
      meleeRange: 86,
      relocation: {
        startFrame: 4,
        endFrame: 6,
        distanceXRatio: 0.04,
      },
      frameBoxes: {
        5: {
          hitboxes: [
            hitbox({
              x: 24,
              y: -84,
              width: 36,
              height: 18,
              damage: 84,
              hitstun: 14,
              knockbackX: 11,
              launchY: 5,
            }),
          ],
        },
      },
    },
    punchFinisher: {
      id: 'punchFinisher',
      label: 'Glitch Break',
      button: 'punch',
      startup: 5,
      active: 4,
      recovery: 13,
      cooldownSeconds: 0,
      animationStance: 'attack1c',
      meleeRange: 96,
      relocation: {
        startFrame: 4,
        endFrame: 7,
        distanceXRatio: 0.045,
      },
      frameBoxes: {
        5: {
          hitboxes: [
            hitbox({
              x: 28,
              y: -86,
              width: 40,
              height: 20,
              damage: 94,
              hitstun: 15,
              knockbackX: 12,
              launchY: 5,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Static Slice',
      button: 'kick',
      startup: 4,
      active: 32,
      recovery: 8,
      cooldownSeconds: 0.9,
      meleeRange: 86,
      rootVelocityX: 5.6,
      phaseThroughProjectiles: true,
      finishOnHit: true,
      frameBoxes: {
        ...Object.fromEntries(Array.from({ length: 32 }, (_, index) => [
          index + 4,
          {
            hitboxes: [
              hitbox({
                x: 20,
                y: -82,
                width: 40,
                height: 20,
                damage: 92,
                hitstun: 13,
                knockbackX: 10,
                launchY: 4,
              }),
            ],
          },
        ])),
      },
    },
    special: {
      id: 'special',
      label: 'Reality Fold',
      button: 'special',
      startup: 19,
      active: 5,
      recovery: 18,
      cooldownSeconds: 0,
      meleeRange: 220,
      multiHit: true,
      followUpMoveId: 'specialC',
      followUpWindowFrames: 60,
      followUpExpireCooldownSeconds: 2,
      specialSequence: {
        buildUpFrames: 18,
        animationBuildUpFrames: 9,
        buildUpAnimation: 'special',
        pauseFrames: 14,
        skipToFollowThroughOnSpecialInput: true,
        zoomScale: 1.78,
      },
      relocations: [
        {
          startFrame: 1,
          endFrame: 18,
          distanceXRatio: 0.25,
          distanceY: -190,
        },
        {
          startFrame: 19,
          endFrame: 21,
          fromDistanceXRatio: 0.25,
          distanceXRatio: 0.3,
          fromDistanceY: -190,
          distanceY: 0,
        },
      ],
      frameBoxes: {
        20: {
          hitboxes: [
            hitbox({
              x: -20,
              y: -120,
              width: 180,
              height: 120,
              damage: 38,
              hitstun: 10,
              knockbackX: 0,
            }),
          ],
          hurtboxes: [{ x: -22, y: -104, width: 48, height: 104 }],
        },
        21: {
          hitboxes: [
            hitbox({
              x: -18,
              y: -120,
              width: 184,
              height: 120,
              damage: 38,
              hitstun: 10,
              knockbackX: 0,
            }),
          ],
          hurtboxes: [{ x: -22, y: -104, width: 48, height: 104 }],
        },
        22: {
          hitboxes: [
            hitbox({
              x: -16,
              y: -122,
              width: 190,
              height: 122,
              damage: 42,
              hitstun: 16,
              knockbackX: 12,
              launchY: 7,
            }),
          ],
          hurtboxes: [{ x: -22, y: -104, width: 48, height: 104 }],
        },
      },
    },
    specialC: {
      id: 'specialC',
      label: 'Reality Fold C',
      button: 'special',
      startup: 5,
      active: 1,
      recovery: 16,
      cooldownSeconds: 4,
      animationStance: 'special-c',
      projectile: {
        sprite: 'characters/distorted09/animations/special-b',
        tier: 2,
        rotateToVelocity: false,
        spawnFrame: 5,
        lifetimeFrames: 42,
        spriteScale: 1,
        animationFrameDurationFrames: 2,
        offsetX: 84,
        offsetY: -72,
        speed: 13,
        minimumDistanceRatio: 0.55,
        maximumDistanceRatio: 0.55,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -44,
          y: -54,
          width: 88,
          height: 54,
          damage: 78,
          hitstun: 17,
          knockbackX: 12,
          launchY: 6,
        }),
      },
    },
  },
};

const quaneshalatonya: CharacterDefinition = {
  id: 'quaneshalatonya',
  name: 'Quaneshalatonya',
  palette: {
    primary: '#ff78b0',
    accent: '#ffd670',
    shadow: '#4d1437',
  },
  sprites: {
    portrait: '/characters/quaneshalatonya/portrait.png',
    renderHeight: 152,
  },
  bot: {
    aggressiveness: 0.58,
    arenaMovement: {
      preferredDistanceMultiplier: 1,
      approachBias: 0.62,
      retreatBias: 0.42,
      jumpInChance: 0.36,
      dashJumpForwardChance: 0.5,
      dashJumpBackwardChance: 0.28,
    },
    skillChoice: {
      punchWeight: 1.1,
      kickWeight: 1,
      specialWeight: 1.04,
      attackCadenceMultiplier: 0.96,
    },
    defense: {
      blockChance: 0.88,
      projectileDodgeChance: 0.52,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 980,
    movement: {
      walkSpeed: 4.2,
      jumpVelocity: 18.2,
      gravity: 1.05,
      dash: {
        distance: 116,
        speed: 9.667,
        lift: 6.4,
      },
    },
    pushWidth: 23,
  },
  standingBoxes: {
    hurtboxes: [{ x: -21, y: -108, width: 42, height: 108 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -23, y: -94, width: 46, height: 94 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Crown Flick',
      button: 'punch',
      startup: 3,
      active: 2,
      recovery: 9,
      cooldownSeconds: 0.5,
      frameBoxes: {
        3: {
          hitboxes: [
            hitbox({
              x: 16,
              y: -88,
              width: 24,
              height: 14,
              damage: 58,
              hitstun: 11,
              knockbackX: 7,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Velvet Heel',
      button: 'kick',
      startup: 5,
      active: 3,
      recovery: 11,
      cooldownSeconds: 0.85,
      meleeRange: 172,
      phaseThroughProjectiles: true,
      relocation: {
        startFrame: 4,
        endFrame: 7,
        distanceXRatio: 0.16,
      },
      hitboxAnchor: 'attack-origin',
      frameBoxes: {
        5: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -74,
              width: 32,
              height: 18,
              damage: 88,
              hitstun: 13,
              knockbackX: 10,
              launchY: 5,
            }),
          ],
        },
      },
    },
    special: {
      id: 'special',
      label: 'Holy Heal',
      button: 'special',
      startup: 6,
      active: 1,
      recovery: 26,
      cooldownSeconds: 6,
      rootVelocityX: 0,
      animationStance: 'special',
      startsReady: true,
      selfHealRatio: 0.125,
      healAura: 'holy',
      grantsInvulnerability: true,
    },
  },
};

const corgi: CharacterDefinition = {
  id: 'corgi',
  name: 'CommanderCorgi',
  palette: {
    primary: '#c8894b',
    accent: '#fff0c7',
    shadow: '#4d2f1b',
  },
  sprites: {
    portrait: '/characters/corgi/animations/idle/0.png',
    renderHeight: 110,
    stanceRenderOffsets: {
      attack1a: { y: -8 },
      attack1b: { y: -8 },
      attack1c: { y: -8 },
      attack1d: { y: -8 },
    },
  },
  bot: {
    aggressiveness: 0.82,
    arenaMovement: {
      preferredDistanceMultiplier: 0.74,
      approachBias: 0.92,
      retreatBias: 0.18,
      jumpInChance: 0.58,
      dashJumpForwardChance: 0.76,
      dashJumpBackwardChance: 0.14,
    },
    skillChoice: {
      punchWeight: 1.5,
      kickWeight: 1.1,
      specialWeight: 0.95,
      attackCadenceMultiplier: 0.88,
    },
    defense: {
      blockChance: 0.72,
      projectileDodgeChance: 0.38,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 960,
    movement: {
      walkSpeed: 5.1,
      jumpVelocity: 15.6,
      gravity: 1.18,
      dash: {
        distance: 102,
        speed: 10.2,
        lift: 4.2,
      },
    },
    pushWidth: 20,
  },
  standingBoxes: {
    hurtboxes: [{ x: -26, y: -72, width: 52, height: 72 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -64, width: 48, height: 64 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Snout Boop',
      button: 'punch',
      startup: 3,
      active: 3,
      recovery: 8,
      cooldownSeconds: 0.45,
      meleeRange: 48,
      animationStance: 'attack1a',
      followUpMoveId: 'punchFollowUp',
      multiHit: true,
      relocation: {
        startFrame: 2,
        endFrame: 4,
        distanceXRatio: 0.03,
      },
      frameBoxes: {
        3: {
          hitboxes: [
            hitbox({
              x: 18,
              y: -46,
              width: 24,
              height: 12,
              damage: 2,
              hitstun: 9,
              knockbackX: 7,
            }),
          ],
        },
        4: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -46,
              width: 24,
              height: 12,
              damage: 2,
              hitstun: 9,
              knockbackX: 7,
            }),
          ],
        },
      },
    },
    punchFollowUp: {
      id: 'punchFollowUp',
      label: 'Snout Boop 2',
      button: 'punch',
      startup: 3,
      active: 3,
      recovery: 8,
      cooldownSeconds: 0,
      meleeRange: 56,
      animationStance: 'attack1b',
      followUpMoveId: 'punchFinisher',
      multiHit: true,
      relocation: {
        startFrame: 2,
        endFrame: 4,
        distanceXRatio: 0.034,
      },
      frameBoxes: {
        3: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -48,
              width: 26,
              height: 12,
              damage: 2,
              hitstun: 9,
              knockbackX: 8,
            }),
          ],
        },
        4: {
          hitboxes: [
            hitbox({
              x: 22,
              y: -48,
              width: 26,
              height: 12,
              damage: 2,
              hitstun: 9,
              knockbackX: 8,
            }),
          ],
        },
      },
    },
    punchFinisher: {
      id: 'punchFinisher',
      label: 'Snout Boop 3',
      button: 'punch',
      startup: 4,
      active: 3,
      recovery: 9,
      cooldownSeconds: 0,
      meleeRange: 64,
      animationStance: 'attack1c',
      followUpMoveId: 'punchCross',
      multiHit: true,
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.04,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 22,
              y: -50,
              width: 28,
              height: 12,
              damage: 2,
              hitstun: 10,
              knockbackX: 9,
            }),
          ],
        },
        5: {
          hitboxes: [
            hitbox({
              x: 24,
              y: -50,
              width: 28,
              height: 12,
              damage: 2,
              hitstun: 10,
              knockbackX: 9,
            }),
          ],
        },
      },
    },
    punchCross: {
      id: 'punchCross',
      label: 'Snout Boop 4',
      button: 'punch',
      startup: 4,
      active: 3,
      recovery: 11,
      cooldownSeconds: 0,
      meleeRange: 78,
      animationStance: 'attack1d',
      multiHit: true,
      relocation: {
        startFrame: 3,
        endFrame: 7,
        distanceXRatio: 0.075,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 24,
              y: -50,
              width: 30,
              height: 14,
              damage: 2,
              hitstun: 11,
              knockbackX: 12,
            }),
          ],
        },
        5: {
          hitboxes: [
            hitbox({
              x: 26,
              y: -50,
              width: 32,
              height: 14,
              damage: 2,
              hitstun: 11,
              knockbackX: 12,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Ankle Biter',
      button: 'kick',
      startup: 1,
      active: 4,
      recovery: 10,
      cooldownSeconds: 2,
      meleeRange: 142,
      phaseThroughProjectiles: true,
      passThroughOpponent: true,
      animationStance: 'attack2',
      relocation: {
        startFrame: 1,
        endFrame: 4,
        distanceXRatio: 0.21,
      },
      hitboxAnchor: 'attack-origin',
      frameBoxes: {
        1: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -34,
              width: 30,
              height: 14,
              damage: 86,
              hitstun: 12,
              knockbackX: 10,
              launchY: 3,
            }),
          ],
        },
      },
    },
    special: {
      id: 'special',
      label: 'Zoomies',
      button: 'special',
      startup: 1,
      active: 5,
      recovery: 14,
      cooldownSeconds: 5,
      meleeRange: 84,
      passThroughOpponent: true,
      stealthFrames: 120,
      rootVelocityX: 7.0,
      frameBoxes: {
        1: {
          hitboxes: [
            hitbox({
              x: 24,
              y: -40,
              width: 36,
              height: 16,
              damage: 112,
              hitstun: 17,
              knockbackX: 14,
              launchY: 5,
            }),
          ],
          hurtboxes: [{ x: -28, y: -70, width: 56, height: 70 }],
        },
      },
      relocation: {
        startFrame: 1,
        endFrame: 5,
        distanceXRatio: 0.315,
      },
    },
  },
};

const leechingshjt: CharacterDefinition = {
  id: 'leechingshjt',
  name: 'LeechingShjt',
  palette: {
    primary: '#6a274a',
    accent: '#58d8ff',
    shadow: '#140f1d',
  },
  sprites: {
    portrait: '/characters/LeechingShjt/profile.png',
    renderHeight: 117,
    assetRoot: 'LeechingShjt',
    stanceRenderOffsets: {
      // This pack's frames sit a bit high in their canvas; pull them down.
      idle: { y: 12 },
      walk: { y: 12 },
      jump: { y: 12 },
      dash: { y: 12 },
      block: { y: 12 },
      hurt: { y: 12 },
      attack1: { y: 12 },
      attack1a: { y: 12 },
      attack1b: { y: 12 },
      attack1c: { y: 12 },
      attack2: { y: 12 },
      attack3: { y: 12 },
      special: { y: 12 },
      // KO frames are even higher; pull further down.
      ko: { y: 18 },
      win: { y: 12 },
    },
  },
  bot: {
    aggressiveness: 0.68,
    arenaMovement: {
      preferredDistanceMultiplier: 0.92,
      approachBias: 0.78,
      retreatBias: 0.24,
      jumpInChance: 0.42,
      dashJumpForwardChance: 0.62,
      dashJumpBackwardChance: 0.2,
    },
    skillChoice: {
      punchWeight: 1.2,
      kickWeight: 1.05,
      specialWeight: 1.1,
      attackCadenceMultiplier: 0.9,
    },
    defense: {
      blockChance: 0.78,
      projectileDodgeChance: 0.44,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 995,
    movement: {
      walkSpeed: 4.45,
      jumpVelocity: 17.6,
      gravity: 1.1,
      dash: {
        distance: 150,
        speed: 7.2,
        lift: 5.4,
      },
    },
    pushWidth: 22,
  },
  standingBoxes: {
    hurtboxes: [{ x: -21, y: -104, width: 42, height: 104 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -23, y: -92, width: 46, height: 92 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Leech Jab',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 9,
      cooldownSeconds: 0,
      animationStance: 'attack1a',
      followUpMoveId: 'punchFollowUp',
      meleeRange: 72,
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.035,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 18,
              y: -78,
              width: 26,
              height: 16,
              damage: 2,
              hitstun: 10,
              knockbackX: 1,
            }),
          ],
        },
      },
    },
    punchFollowUp: {
      id: 'punchFollowUp',
      label: 'Leech Cut',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 9,
      cooldownSeconds: 0,
      animationStance: 'attack1b',
      followUpMoveId: 'punchFinisher',
      meleeRange: 80,
      relocation: {
        startFrame: 3,
        endFrame: 5,
        distanceXRatio: 0.04,
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 20,
              y: -80,
              width: 30,
              height: 16,
              damage: 2,
              hitstun: 10,
              knockbackX: 1,
            }),
          ],
        },
      },
    },
    punchFinisher: {
      id: 'punchFinisher',
      label: 'Leech Rip',
      button: 'punch',
      startup: 5,
      active: 2,
      recovery: 11,
      cooldownSeconds: 0,
      animationStance: 'attack1c',
      meleeRange: 88,
      relocation: {
        startFrame: 4,
        endFrame: 6,
        distanceXRatio: 0.045,
      },
      frameBoxes: {
        5: {
          hitboxes: [
            hitbox({
              x: 22,
              y: -82,
              width: 34,
              height: 18,
              damage: 2,
              hitstun: 12,
              knockbackX: 18,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Drain Slice',
      button: 'kick',
      startup: 6,
      active: 52,
      recovery: 8,
      cooldownSeconds: 0.8,
      meleeRange: 104,
      multiHit: true,
      phaseThroughProjectiles: true,
      loopAnimation: true,
      animationFrameDurationFrames: 3,
      relocation: {
        startFrame: 4,
        endFrame: 57,
        distanceXRatio: 0.28,
      },
      frameBoxes: {
        ...Object.fromEntries(Array.from({ length: 51 }, (_, index) => [
          index + 6,
          {
            hitboxes: [
              hitbox({
                x: 18,
                y: -76,
                width: 58,
                height: 22,
                damage: 1,
                hitstun: 7,
                knockbackX: 0,
              }),
            ],
          },
        ])),
        57: {
          hitboxes: [
            hitbox({
              x: 22,
              y: -78,
              width: 64,
              height: 24,
              damage: 8,
              hitstun: 13,
              knockbackX: 0,
            }),
          ],
        },
      },
    },
    special: {
      id: 'special',
      label: 'Blood Rite',
      button: 'special',
      startup: 54,
      active: 25,
      recovery: 24,
      cooldownSeconds: 4,
      animationStance: 'special',
      specialSequence: {
        buildUpFrames: 54,
        animationBuildUpFrames: 9,
        buildUpAnimation: 'special',
        pauseFrames: 24,
        zoomScale: 1.78,
      },
      projectile: {
        sprite: 'characters/LeechingShjt/Animations/special-projectile-1',
        spriteOptions: [
          'characters/LeechingShjt/Animations/special-projectile-1',
          'characters/LeechingShjt/Animations/special-projectile-2',
          'characters/LeechingShjt/Animations/special-projectile-3',
          'characters/LeechingShjt/Animations/special-projectile-4',
          'characters/LeechingShjt/Animations/special-projectile-banana',
          'characters/LeechingShjt/Animations/special-projectile-banana',
          'characters/LeechingShjt/Animations/special-projectile-banana',
          'characters/LeechingShjt/Animations/special-projectile-banana',
        ],
        spriteOptionEffects: {
          'characters/LeechingShjt/Animations/special-projectile-banana': {
            healTargetRatio: 0.125,
            hitbox: hitbox({
              x: -18,
              y: -18,
              width: 36,
              height: 36,
              damage: 1,
              hitstun: 0,
              knockbackX: 0,
            }),
          },
        },
        tier: 2,
        spawnFrame: 54,
        shotCount: 2,
        shotIntervalFrames: 24,
        lifetimeFrames: 90,
        spriteScale: 0.35,
        animationFrameDurationFrames: 6,
        offsetX: 30,
        offsetY: -76,
        speed: 8.4,
        targeting: 'opponent',
        homing: true,
        rotateToVelocity: false,
        tumbleRotation: true,
        minimumDistanceRatio: 0.75,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -18,
          y: -18,
          width: 36,
          height: 36,
          damage: 62,
          hitstun: 14,
          knockbackX: 8,
          launchY: 4,
        }),
      },
    },
  },
};

const mrsdoc: CharacterDefinition = {
  id: 'mrsdoc',
  name: 'MrsDoc',
  palette: {
    primary: '#c16f56',
    accent: '#ffe08c',
    shadow: '#3f1f1a',
  },
  sprites: {
    portrait: '/characters/mrsdoc/profile.png',
    renderHeight: 108,
    assetRoot: 'mrsdoc',
    stanceAliases: {
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 0.58,
    arenaMovement: {
      preferredDistanceMultiplier: 0.88,
      approachBias: 0.64,
      retreatBias: 0.28,
      jumpInChance: 0.34,
      dashJumpForwardChance: 0.48,
      dashJumpBackwardChance: 0.22,
    },
    skillChoice: {
      punchWeight: 1.18,
      kickWeight: 1.04,
      specialWeight: 1.08,
      attackCadenceMultiplier: 0.94,
    },
    defense: {
      blockChance: 0.82,
      projectileDodgeChance: 0.46,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 1005,
    movement: {
      walkSpeed: 4.4,
      jumpVelocity: 17.8,
      gravity: 1.08,
      dash: {
        distance: 104,
        speed: 9.1,
        lift: 5.2,
      },
    },
    pushWidth: 23,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -102, width: 44, height: 102 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -90, width: 48, height: 90 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Clinic Tap',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 9,
      cooldownSeconds: 0.5,
      meleeRange: 74,
      projectile: {
        sprite: 'mrsdoc/attack1-projectile',
        tier: 1,
        alpha: 0.6,
        spriteScale: 0.7,
        offsetX: 28,
        offsetY: -64,
        speed: 10,
        minimumDistanceRatio: 0.55,
        maximumDistanceRatio: 0.55,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -8,
          y: -8,
          width: 16,
          height: 16,
          damage: 33,
          hitstun: 8,
          knockbackX: 6,
        }),
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 18,
              y: -74,
              width: 28,
              height: 16,
              damage: 64,
              hitstun: 10,
              knockbackX: 8,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Case Closed',
      button: 'kick',
      startup: 1,
      active: 4,
      recovery: 11,
      cooldownSeconds: 0.82,
      phaseThroughProjectiles: true,
      projectile: {
        sprite: 'projectiles/mrsdoc/smite-beam',
        tier: 2,
        // Projectile is visually present and "active" for the whole window.
        spawnFrame: 2,
        // 4-frame animation * 12 frames-per-frame = 48 frames to play the full sequence.
        lifetimeFrames: 48,
        persistsOnHit: true,
        // Two hits across the duration (frames 2 and ~4).
        hitIntervalFrames: 2,
        maxHits: 2,
        spriteScale: 2,
        // Slow down the beam animation.
        animationFrameDurationFrames: 12,
        // Always land on the enemy.
        spawnAnchor: 'opponent',
        spawnYAnchor: 'ground',
        offsetX: 0,
        // Bottom-align the 128px sprite to ground at 2x scale (origin is centered).
        offsetY: -128,
        speed: 0.001,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        rotateToVelocity: false,
        alpha: 0.4,
        hitbox: hitbox({
          // Match the beam's footprint and keep overlap generous.
          x: -34,
          y: -128,
          width: 68,
          height: 156,
          damage: 80,
          hitstun: 11,
          knockbackX: 10,
          launchY: 3,
        }),
      },
    },
    special: {
      id: 'special',
      label: 'Emergency Rounds',
      button: 'special',
      startup: 1,
      // Keep invulnerability to ~1.5s (90 frames at 60fps).
      active: 60,
      recovery: 29,
      cooldownSeconds: 6,
      meleeRange: 92,
      rootVelocityX: 0,
      selfHealRatio: 0.125,
      healAura: 'holy',
      phaseThroughProjectiles: true,
      grantsInvulnerability: true,
      multiHit: true,
      frameBoxes: {
        1: {
          hitboxes: [
            hitbox({
              x: 10,
              y: -86,
              width: 64,
              height: 26,
              damage: 38,
              hitstun: 12,
              knockbackX: 18,
              launchY: 3,
            }),
          ],
          hurtboxes: [{ x: -20, y: -100, width: 50, height: 100 }],
        },
        ...Object.fromEntries(
          // Pulsing close-range knockback during the cast.
          Array.from({ length: 15 }, (_, index) => {
            const frame = 6 + index * 6;
            return [
              frame,
              {
                hitboxes: [
                  hitbox({
                    x: 8,
                    y: -92,
                    width: 72,
                    height: 34,
                    damage: 1,
                    hitstun: 8,
                    knockbackX: 14,
                    launchY: 2,
                  }),
                ],
              },
            ] as const;
          }),
        ),
      },
    },
  },
};

const anjokbal: CharacterDefinition = {
  id: 'anjokbal',
  name: 'Anjokbal',
  palette: {
    primary: '#5fbf8e',
    accent: '#f6d36a',
    shadow: '#173229',
  },
  sprites: {
    portrait: '/characters/anjokbal/profile.png',
    renderHeight: 114,
    assetRoot: 'anjokbal',
    stanceAliases: {
      block: ['idle'],
    },
  },
  bot: {
    aggressiveness: 0.66,
    arenaMovement: {
      preferredDistanceMultiplier: 0.9,
      approachBias: 0.72,
      retreatBias: 0.22,
      jumpInChance: 0.38,
      dashJumpForwardChance: 0.56,
      dashJumpBackwardChance: 0.24,
    },
    skillChoice: {
      punchWeight: 1.16,
      kickWeight: 1.08,
      specialWeight: 1.12,
      attackCadenceMultiplier: 0.9,
    },
    defense: {
      blockChance: 0.8,
      projectileDodgeChance: 0.48,
      meleeBlockReactionFrames: 1,
      projectileBlockReactionFrames: 4,
    },
  },
  stats: {
    maxHealth: 1010,
    movement: {
      walkSpeed: 4.35,
      jumpVelocity: 17.7,
      gravity: 1.08,
      dash: {
        distance: 105,
        speed: 9.15,
        lift: 5.1,
      },
    },
    pushWidth: 23,
  },
  standingBoxes: {
    hurtboxes: [{ x: -22, y: -104, width: 44, height: 104 }],
  },
  jumpingBoxes: {
    hurtboxes: [{ x: -24, y: -92, width: 48, height: 92 }],
  },
  moves: {
    punch: {
      id: 'punch',
      label: 'Palm Check',
      button: 'punch',
      startup: 4,
      active: 2,
      recovery: 9,
      cooldownSeconds: 0.5,
      meleeRange: 76,
      projectile: {
        sprite: 'anjokbal/attack1-projectile',
        tier: 1,
        spriteScale: 1,
        offsetX: 28,
        offsetY: -66,
        speed: 10,
        minimumDistanceRatio: 0.55,
        maximumDistanceRatio: 0.55,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -12,
          y: -12,
          width: 24,
          height: 24,
          damage: 34,
          hitstun: 8,
          knockbackX: 6,
        }),
      },
      frameBoxes: {
        4: {
          hitboxes: [
            hitbox({
              x: 18,
              y: -76,
              width: 28,
              height: 16,
              damage: 66,
              hitstun: 10,
              knockbackX: 8,
            }),
          ],
        },
      },
    },
    kick: {
      id: 'kick',
      label: 'Split Appeal',
      button: 'kick',
      startup: 6,
      active: 3,
      recovery: 11,
      cooldownSeconds: 5,
      meleeRange: 86,
      projectile: {
        sprite: 'characters/anjokbal/animations/attack2-projectile',
        tier: 2,
        rotateToVelocity: false,
        spawnFrame: 6,
        lifetimeFrames: 112,
        persistsOnHit: true,
        hitIntervalFrames: 10,
        spriteScale: 1.2,
        animationFrameDurationFrames: 16,
        spawnAnchor: 'opponent',
        offsetX: 0,
        offsetY: -40,
        speed: 0.001,
        targeting: 'opponent',
        minimumDistanceRatio: 1,
        apexHeight: 0,
        landing: 'origin',
        hitbox: hitbox({
          x: -44,
          y: 6,
          width: 88,
          height: 60,
          damage: 18,
          chipDamage: 0,
          hitstun: 7,
          knockbackX: 0,
          launchY: 6,
        }),
      },
    },
    special: {
      id: 'special',
      label: 'Leaf Mend',
      button: 'special',
      startup: 1,
      active: 299,
      recovery: 0,
      cooldownSeconds: 6,
      rootVelocityX: 0,
      animationStance: 'special',
      startsReady: true,
      healAura: 'leaf',
      channelSpecial: {
        durationFrames: 300,
        initialMode: 'heal',
        toggleModes: ['heal', 'drain'],
        tickIntervalFrames: 15,
        channelMoveSpeed: 2.9,
        auraWidthMultiplier: 3,
        auraHeightMultiplier: 1.35,
        healPerSecondRatio: 0.05,
        damagePerSecondRatio: 0.035,
        slowMultiplier: 0.52,
      },
    },
  },
};

export const characterDefinitions: CharacterDefinition[] = [
  // quaneshalatonya,
  paraktaktak,
  digv,
  mcbalut,
  morana,
  distorted,
  corgi,
  leechingshjt,
  mrsdoc,
  anjokbal,
];

export const hiddenCharacterDefinitions: CharacterDefinition[] = [
  mcbalutAnomaly,
];
